# Compile protobufs and push them to npm
version: 2

defaults: &defaults
  working_directory: /root/proto

jobs:
  compile:
    <<: *defaults
    docker:
      - image: grpc/go

    steps:
      - checkout
      - run: 
          name: Compile protobufs
          command: |
            mkdir -p /root/proto/dist
            protoc account_updated.proto --js_out=import_style=commonjs,binary:/root/proto/dist --proto_path=/root/proto/
            protoc user_updated.proto --js_out=import_style=commonjs,binary:/root/proto/dist --proto_path=/root/proto/

      # As an early step, we'll save artifacts instead
      # of pushing them to npm.
      - store_artifacts:
          path: /root/proto/dist

      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    <<: *defaults
    docker:
      - image: circleci/node:11

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - compile
      - publish:
          requires:
            - compile
