# Compile protobufs and push them to npm
version: 2

defaults: &defaults
  working_directory: ~/proto

jobs:
  compile:
    <<: *defaults
    docker:
      - image: grpc/go

    steps:
      - checkout
      - run: 
          name: Compile protobufs
          command: |
            mkdir -p $HOME/proto/dist
            protoc --js_out=import_style=commonjs,binary:dist -I . protos/*.proto

      # As an early step, we'll save artifacts instead
      # of pushing them to npm.
      - store_artifacts:
          path: /root/proto/dist

      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    docker:
      - image: circleci/node:11

    steps:
      - attach_workspace:
          at: ~/proto

      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    docker:
      - image: circleci/node:11

    steps:
      - attach_workspace:
          at: ~/proto

      - run:
          name: Test
          command: npm run lint

  publish:
    <<: *defaults
    docker:
      - image: circleci/node:11

    steps:
      - attach_workspace:
          at: ~/proto

      - run:
          name: Login to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - compile:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - compile
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
