# Compile protobufs and push them to npm
version: 2
jobs:
  compile:
    docker:
      - image: grpc/go

    working_directory: $HOME/proto
    steps:
      - checkout
      - run: 
          name: Compile protobufs
          command: |
            protoc account_updated.proto --js_out=import_style=commonjs,binary:/tmp/proto --proto_path=$HOME/proto/
            protoc user_updated.proto --js_out=import_style=commonjs,binary:/tmp/proto --proto_path=$HOME/proto/

      # As an early step, we'll save artifacts instead
      # of pushing them to npm.
      - store_artifacts:
          path: /tmp/proto

workflows:
  version: 2
  build:
    jobs:
      - compile